services:
  postgres:
    container_name: postgres-sql-betalecteur
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: beta_lecteur
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-project
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-betalecteur
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"



networks:
  spring-project:
    driver: bridge

volumes:
  postgres:
    driver: local
